services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: ["/bin/bash", "-c", "\
      ollama serve & \
      sleep 5 && \
      ollama pull gemma:2b && \
      wait"]
    restart: unless-stopped
    healthcheck:
      disable: true # Keep healthcheck disabled

  backend:
    build: ./backend
    container_name: multi-agent-backend
    ports:
      - "5000:5000"
    environment:
      - OLLAMA_HOST=http://ollama-server:11434
    depends_on:
      ollama:
        condition: service_started # Changed to service_started
    restart: unless-stopped

volumes:
  ollama_models:
    driver: local