services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    entrypoint: ["/bin/bash", "-c", "\
      ollama serve & \
      sleep 5 && \
      ollama pull gemma:2b && \
      wait"]
    restart: unless-stopped
    healthcheck:
      # test: ["CMD-SHELL", "curl -f http://localhost:11434/api/tags || exit 1"]
      # interval: 20s
      # timeout: 5s
      # retries: 5
      disable: true # Disable healthcheck for Ollama service
  
  backend:
    build: ./backend # Build from the Dockerfile in the 'backend' directory
    container_name: multi-agent-backend
    ports:
      - "5000:5000" # Expose port 5000 for the mobile app to connect
    environment:
      # Pass the Ollama host to the backend container
      # This allows the backend to find the Ollama service within the Docker network
      - OLLAMA_HOST=http://ollama-server:11434
    depends_on:
      - ollama # Ensure Ollama service is started before the backend
    restart: unless-stopped

volumes:
  ollama_models:
    driver: local
